# Generated by Django 5.0.5 on 2024-06-19 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('mobile_no', models.CharField(max_length=13)),
                ('college', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('image', models.FileField(upload_to='Student_detail')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='std_section.course')),
            ],
        ),
    ]
