# Generated by Django 5.0.5 on 2024-06-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_section', '0002_student_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_detail',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='student_detail',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='student_detail',
            name='image',
            field=models.FileField(upload_to='Student_detail/'),
        ),
    ]
